### ISSUE TITLE
Plex fetch failed

### ISSUE THREAD

**Issue by Retract1822** [connorgallopo/Tracearr#44]
Raised in #40 but I feel like it warrants it's own issue since it's different from the other issue

> I am having the same problem. Signing in with plex does not work, I get the below:
> 
> <img width="2178" height="1304" alt="Image" src="https://github.com/user-attachments/assets/78c94d0e-f7ce-4ea8-a2e6-ec6aba3a2b5a" />
> 
> EDIT: Sorry forgot to add, that the plex container is running on the same network as the tracearr container and it can telnet/ping the plex container (after adding in telnet package for a manual test) 

 _Originally posted by @Retract1822 in [#40](https://github.com/connorgallopo/Tracearr/issues/40#issuecomment-3665772317)_

I'm not sure whether there are some ENV vars required? I'm using traefik as a reverse proxy for the server and In my docker compose I've specified:

- TRUST_PROXY=true
- CORS_ORIGIN=https://$fqdn

**Comment by connorgallopo** [comment]
This should be resolved on the `next` tag @Retract1822

**Comment by ghost** [comment]
@connorgallopo  - I just tried the next supervised tag but its still not working for me. My Plex is running in docker but im using a custom URL which runs through my reverse proxy so https://plex.mydomain.com and it fails to connect.

The server detection is showing my server in the list, its showing all the docker IPs along with my custom domain and all of them fail to connect no matter which one I pick.

<img width="1430" height="1166" alt="Image" src="https://github.com/user-attachments/assets/cacefd6c-2746-47ea-8fef-79c598e95ed8" />

**Comment by connorgallopo** [comment]
@rdavey228 do you have the sha of the tag you are on?

**Comment by connorgallopo** [comment]
I pushed another fix this evening - that was a url param I was missing in my first plex call.. So you might have just missed that

**Comment by ghost** [comment]
I just updated to the latest supervised-next but still getting the same issue.

**Comment by Retract1822** [comment]
I tried using `ghcr.io/connorgallopo/tracearr:supervised-nightly-20251218` and it works when I enter a custom URL

I have the same as @rdavey228 where my Tracearr is behind a proxy so accessible at https://plex.my.local.domain, since all the other fetched URLs have the plex port behind them I think they are failing the HTTPS check (not sure if that's the resaon for the failure but just a guess). Putting that in as the custom URL as mentioned above worked straight away, thank you

**Comment by ghost** [comment]
> I tried using `ghcr.io/connorgallopo/tracearr:supervised-nightly-20251218` and it works when I enter a custom URL
> 
> I have the same as [@rdavey228](https://github.com/rdavey228) where my Tracearr is behind a proxy so accessible at https://plex.my.local.domain, since all the other fetched URLs have the plex port behind them I think they are failing the HTTPS check (not sure if that's the resaon for the failure but just a guess). Putting that in as the custom URL as mentioned above worked straight away, thank you

What are you entering for the custom domain?

I've tried the nightly version you suggested above and I've then entered https://plex.mydomain.com as the custom domain but it still fails.

This a publicly facing domain I'm using.

**Comment by Retract1822** [comment]
Hey, I entered https://plex.mylocaldomain.com (my domain is not publicly facing). Though I purged everything first, i.e. I removed and recreated all the data directories so I was setting it up from scratch and then selected sign in with Plex and entered the custom URL I mentioned and that seemed to work

**Comment by ghost** [comment]
> Hey, I entered https://plex.mylocaldomain.com (my domain is not publicly facing). Though I purged everything first, i.e. I removed and recreated all the data directories so I was setting it up from scratch and then selected sign in with Plex and entered the custom URL I mentioned and that seemed to work

Ok, that did it. Clearing out the directories like you said then entering https://plex.mydomain.com/ worked!

Thanks!

**Comment by connorgallopo** [comment]
Gonna close and tag as "Documentation" to cover this in the knowledge base when we have one! Cheers!
