### ISSUE TITLE
[Bug] Discord Notifications - v1.3.8-beta.5

### ISSUE THREAD

**Issue by jjjonesjr33** [connorgallopo/Tracearr#48]
Issue seems to be on notifications that post only. For example 

<img width="370" height="1167" alt="Image" src="https://github.com/user-attachments/assets/95e3aaba-59fe-4ebf-9dff-62546238ae86" />

The format needs to be fixed, as well as why it posted the same message 3 times. Good news though, in the GUI it only shows 1 violation

**Comment by jjjonesjr33** [comment]
This seems to be for any violation that comes accross as well. Example:

<img width="345" height="1043" alt="Image" src="https://github.com/user-attachments/assets/99d37597-efb1-484c-898a-02f3e1ffa71c" />

**Comment by connorgallopo** [comment]
@jjjonesjr33 This should be fixed in the latest beta!

**Comment by jjjonesjr33** [comment]
@connorgallopo still broken in `supervised-v1.3.9-beta.6`

<img width="367" height="563" alt="Image" src="https://github.com/user-attachments/assets/5794199d-5daa-4625-9716-acfc08608993" />

**Comment by connorgallopo** [comment]
Do you have multiple Geo rules?

**Comment by connorgallopo** [comment]
` SELECT id, name, type, server_user_id FROM rules WHERE type = 'geo_restriction';`
